// lib/data.ts
export interface Movie {
  id: string;
  title: string;
  year: number;
  director: string;
  genre: string;
  myRating: number;
  imdbRating: number;
}

export const GENRES = ['All', 'Sci-Fi', 'Crime', 'Thriller', 'Action', 'Drama', 'War', 'Romance', 'Horror', 'Animation', 'Comedy', 'History'];

export const mockMovies: Movie[] = [
  { id: '1', title: '13 Hours Secret Soldiers', year: 2016, director: 'Michael Bay', genre: 'War', myRating: 8.2, imdbRating: 7.3 },
  { id: '2', title: '1917', year: 2019, director: 'Sam Mendes', genre: 'War', myRating: 7.5, imdbRating: 8.2 },
  { id: '3', title: 'A Hidden Life', year: 2019, director: 'Terrence Malick', genre: 'Drama', myRating: 0, imdbRating: 7.4 },
  { id: '4', title: 'After We Collided', year: 2020, director: 'Roger Kumble', genre: 'Romance', myRating: 0, imdbRating: 5.0 },
  { id: '5', title: 'All Quiet On The Western Front', year: 2022, director: 'Edward Berger', genre: 'War', myRating: 0, imdbRating: 7.8 },
  { id: '6', title: 'Allied', year: 2016, director: 'Robert Zemeckis', genre: 'War', myRating: 0, imdbRating: 7.1 },
  { id: '7', title: 'American Made', year: 2017, director: 'Doug Liman', genre: 'Crime', myRating: 0, imdbRating: 7.1 },
  { id: '8', title: 'Anyone But You', year: 2023, director: 'Will Gluck', genre: 'Romance', myRating: 0, imdbRating: 6.2 },
  { id: '9', title: 'Ballerina', year: 2023, director: 'Lee Chung-hyun', genre: 'Action', myRating: 0, imdbRating: 6.3 },
  { id: '10', title: 'Batman Vs Superman', year: 2016, director: 'Zack Snyder', genre: 'Action', myRating: 0, imdbRating: 6.5 },
  { id: '11', title: 'Battleship', year: 2012, director: 'Peter Berg', genre: 'Sci-Fi', myRating: 0, imdbRating: 5.8 },
  { id: '12', title: 'Baywatch', year: 2017, director: 'Seth Gordon', genre: 'Action', myRating: 0, imdbRating: 5.5 },
  { id: '13', title: 'Benjamin Button', year: 2008, director: 'David Fincher', genre: 'Drama', myRating: 0, imdbRating: 7.8 },
  { id: '14', title: 'Berlin', year: 2023, director: 'Álex Pina', genre: 'Crime', myRating: 0, imdbRating: 7.0 },
  { id: '15', title: 'Black Adam', year: 2022, director: 'Jaume Collet-Serra', genre: 'Action', myRating: 0, imdbRating: 6.2 },
  { id: '16', title: 'Blood Brothers', year: 2007, director: 'Alexi Tan', genre: 'Crime', myRating: 0, imdbRating: 6.3 },
  { id: '17', title: 'Call Of Duty Makarov', year: 2023, director: 'N/A', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '18', title: 'Captain Phillips', year: 2013, director: 'Paul Greengrass', genre: 'Drama', myRating: 0, imdbRating: 7.8 },
  { id: '19', title: 'Chappie', year: 2015, director: 'Neill Blomkamp', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.8 },
  { id: '20', title: 'Chernobyl', year: 2019, director: 'Johan Renck', genre: 'Drama', myRating: 0, imdbRating: 9.3 },
  { id: '21', title: 'Clean House', year: 2006, director: 'Various', genre: 'Drama', myRating: 0, imdbRating: 6.5 },
  { id: '22', title: 'Culpa Mia', year: 2023, director: 'Domingo González', genre: 'Romance', myRating: 0, imdbRating: 6.2 },
  { id: '23', title: 'Culpa Tuya', year: 2024, director: 'Domingo González', genre: 'Romance', myRating: 0, imdbRating: 6.0 },
  { id: '24', title: 'Deadpool', year: 2016, director: 'Tim Miller', genre: 'Action', myRating: 0, imdbRating: 8.0 },
  { id: '25', title: 'Deep Impact', year: 1998, director: 'Mimi Leder', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.2 },
  { id: '26', title: 'Devil May Cry', year: 2007, director: 'Shin Itagaki', genre: 'Action', myRating: 0, imdbRating: 7.2 },
  { id: '27', title: 'Downfall', year: 2004, director: 'Oliver Hirschbiegel', genre: 'History', myRating: 0, imdbRating: 8.2 },
  { id: '28', title: 'Dunkirk', year: 2017, director: 'Christopher Nolan', genre: 'War', myRating: 0, imdbRating: 7.8 },
  { id: '29', title: 'Elemental', year: 2023, director: 'Peter Sohn', genre: 'Animation', myRating: 0, imdbRating: 7.0 },
  { id: '30', title: 'Elysium', year: 2013, director: 'Neill Blomkamp', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.6 },
  { id: '31', title: 'Endgame', year: 2019, director: 'Russo Brothers', genre: 'Action', myRating: 0, imdbRating: 8.4 },
  { id: '32', title: 'Escape Plan', year: 2013, director: 'Mikael Håfström', genre: 'Action', myRating: 0, imdbRating: 6.7 },
  { id: '33', title: 'Everest', year: 2015, director: 'Baltasar Kormákur', genre: 'Drama', myRating: 0, imdbRating: 7.1 },
  { id: '34', title: 'Everything Everywhere All At Once', year: 2022, director: 'Daniels', genre: 'Sci-Fi', myRating: 0, imdbRating: 7.8 },
  { id: '35', title: 'Evil Dead Rise', year: 2023, director: 'Lee Cronin', genre: 'Horror', myRating: 0, imdbRating: 6.5 },
  { id: '36', title: 'Extraction', year: 2020, director: 'Sam Hargrave', genre: 'Action', myRating: 0, imdbRating: 6.8 },
  { id: '37', title: 'F1 The Movie', year: 2025, director: 'Joseph Kosinski', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '38', title: 'Fall', year: 2022, director: 'Scott Mann', genre: 'Thriller', myRating: 0, imdbRating: 6.4 },
  { id: '39', title: 'Fast & Furious', year: 2001, director: 'Rob Cohen', genre: 'Action', myRating: 0, imdbRating: 6.8 },
  { id: '40', title: 'Fight Club', year: 1999, director: 'David Fincher', genre: 'Drama', myRating: 0, imdbRating: 8.8 },
  { id: '41', title: 'Five Feet Apart', year: 2019, director: 'Justin Baldoni', genre: 'Romance', myRating: 0, imdbRating: 7.1 },
  { id: '42', title: 'Fury', year: 2014, director: 'David Ayer', genre: 'War', myRating: 0, imdbRating: 7.5 },
  { id: '43', title: 'GI Jane', year: 1997, director: 'Ridley Scott', genre: 'Action', myRating: 0, imdbRating: 6.0 },
  { id: '44', title: 'Ghost Of Tsushima', year: 2025, director: 'Chad Stahelski', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '45', title: 'Greenland', year: 2020, director: 'Ric Roman Waugh', genre: 'Thriller', myRating: 0, imdbRating: 6.4 },
  { id: '46', title: 'Hacker', year: 2016, director: 'Akan Satayev', genre: 'Crime', myRating: 0, imdbRating: 6.1 },
  { id: '47', title: 'Harley Quinn', year: 2019, director: 'Justin Halpern', genre: 'Action', myRating: 0, imdbRating: 8.4 },
  { id: '48', title: 'Havoc', year: 2025, director: 'Gareth Evans', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '49', title: 'High Council', year: 2023, director: 'N/A', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '50', title: 'In Youth We Trust', year: 2018, director: 'N/A', genre: 'Drama', myRating: 0, imdbRating: 0 },
  { id: '51', title: 'Inception', year: 2010, director: 'Christopher Nolan', genre: 'Sci-Fi', myRating: 10.0, imdbRating: 8.8 },
  { id: '52', title: 'Infinity War', year: 2018, director: 'Russo Brothers', genre: 'Action', myRating: 0, imdbRating: 8.4 },
  { id: '53', title: 'Interstellar', year: 2014, director: 'Christopher Nolan', genre: 'Sci-Fi', myRating: 9.0, imdbRating: 8.7 },
  { id: '54', title: 'Iron Man', year: 2008, director: 'Jon Favreau', genre: 'Action', myRating: 0, imdbRating: 7.9 },
  { id: '55', title: 'John Wick', year: 2014, director: 'Chad Stahelski', genre: 'Action', myRating: 0, imdbRating: 7.4 },
  { id: '56', title: 'Joker', year: 2019, director: 'Todd Phillips', genre: 'Crime', myRating: 0, imdbRating: 8.4 },
  { id: '57', title: 'Jurassic World', year: 2015, director: 'Colin Trevorrow', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.9 },
  { id: '58', title: 'Kahar', year: 2023, director: 'N/A', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '59', title: 'Kingsman', year: 2014, director: 'Matthew Vaughn', genre: 'Action', myRating: 0, imdbRating: 7.7 },
  { id: '60', title: 'KL Gangster', year: 2011, director: 'Syamsul Yusof', genre: 'Action', myRating: 0, imdbRating: 6.1 },
  { id: '61', title: 'Look Who\'s Back', year: 2015, director: 'David Wnendt', genre: 'Comedy', myRating: 0, imdbRating: 7.0 },
  { id: '62', title: 'Lucifer', year: 2016, director: 'Tom Kapinos', genre: 'Crime', myRating: 0, imdbRating: 8.1 },
  { id: '63', title: 'Mad Max', year: 2015, director: 'George Miller', genre: 'Action', myRating: 0, imdbRating: 8.1 },
  { id: '64', title: 'Malam Terlarang', year: 2024, director: 'N/A', genre: 'Horror', myRating: 0, imdbRating: 0 },
  { id: '65', title: 'Mat Kilau', year: 2022, director: 'Syamsul Yusof', genre: 'History', myRating: 0, imdbRating: 5.4 },
  { id: '66', title: 'Meet Joe Black', year: 1998, director: 'Martin Brest', genre: 'Drama', myRating: 0, imdbRating: 7.2 },
  { id: '67', title: 'Mission Impossible', year: 1996, director: 'Brian De Palma', genre: 'Action', myRating: 0, imdbRating: 7.1 },
  { id: '68', title: 'MK11', year: 2019, director: 'N/A', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '69', title: 'Money Heist', year: 2017, director: 'Álex Pina', genre: 'Crime', myRating: 10.0, imdbRating: 8.2 },
  { id: '70', title: 'Mr & Mrs Smith', year: 2005, director: 'Doug Liman', genre: 'Action', myRating: 0, imdbRating: 6.5 },
  { id: '71', title: 'Need For Speed', year: 2014, director: 'Scott Waugh', genre: 'Action', myRating: 0, imdbRating: 6.4 },
  { id: '72', title: 'Night Comes For Us', year: 2018, director: 'Timo Tjahjanto', genre: 'Action', myRating: 0, imdbRating: 6.9 },
  { id: '73', title: 'Ninja Assassin', year: 2009, director: 'James McTeigue', genre: 'Action', myRating: 0, imdbRating: 6.3 },
  { id: '74', title: 'Now You See Me', year: 2013, director: 'Louis Leterrier', genre: 'Thriller', myRating: 0, imdbRating: 7.2 },
  { id: '75', title: 'Nowhere', year: 2023, director: 'Albert Pintó', genre: 'Thriller', myRating: 0, imdbRating: 6.4 },
  { id: '76', title: 'Olympus Has Fallen', year: 2013, director: 'Antoine Fuqua', genre: 'Action', myRating: 0, imdbRating: 6.5 },
  { id: '77', title: 'Once Upon A Time In Hollywood', year: 2019, director: 'Quentin Tarantino', genre: 'Drama', myRating: 0, imdbRating: 7.6 },
  { id: '78', title: 'Ong Bak', year: 2003, director: 'Prachya Pinkaew', genre: 'Action', myRating: 0, imdbRating: 7.1 },
  { id: '79', title: 'Operation Fortune Ruse De Guere', year: 2023, director: 'Guy Ritchie', genre: 'Action', myRating: 0, imdbRating: 6.3 },
  { id: '80', title: 'Oppenheimer', year: 2023, director: 'Christopher Nolan', genre: 'History', myRating: 0, imdbRating: 8.3 },
  { id: '81', title: 'Our Beloved Summer', year: 2021, director: 'Kim Yoon-jin', genre: 'Romance', myRating: 0, imdbRating: 8.2 },
  { id: '82', title: 'Pacific Rim', year: 2013, director: 'Guillermo del Toro', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.9 },
  { id: '83', title: 'Parasite', year: 2019, director: 'Bong Joon-ho', genre: 'Thriller', myRating: 0, imdbRating: 8.5 },
  { id: '84', title: 'Paskal', year: 2018, director: 'Adrian Teh', genre: 'Action', myRating: 0, imdbRating: 7.7 },
  { id: '85', title: 'Peaky Blinders', year: 2013, director: 'Steven Knight', genre: 'Crime', myRating: 0, imdbRating: 8.8 },
  { id: '86', title: 'Purple Hearts', year: 2022, director: 'Elizabeth Allen Rosenbaum', genre: 'Romance', myRating: 0, imdbRating: 6.7 },
  { id: '87', title: 'Rambo', year: 1982, director: 'Ted Kotcheff', genre: 'Action', myRating: 0, imdbRating: 7.7 },
  { id: '88', title: 'Robocop', year: 1987, director: 'Paul Verhoeven', genre: 'Sci-Fi', myRating: 0, imdbRating: 7.6 },
  { id: '89', title: 'San Andreas', year: 2015, director: 'Brad Peyton', genre: 'Action', myRating: 0, imdbRating: 6.0 },
  { id: '90', title: 'Saving Private Ryan', year: 1998, director: 'Steven Spielberg', genre: 'War', myRating: 0, imdbRating: 8.6 },
  { id: '91', title: 'Shawshank Redemption', year: 1994, director: 'Frank Darabont', genre: 'Drama', myRating: 0, imdbRating: 9.3 },
  { id: '92', title: 'Sheriff', year: 2024, director: 'Syafiq Yusof', genre: 'Crime', myRating: 0, imdbRating: 7.8 },
  { id: '93', title: 'Sicario', year: 2015, director: 'Denis Villeneuve', genre: 'Action', myRating: 10.0, imdbRating: 7.7 },
  { id: '94', title: 'Silent Love', year: 2024, director: 'Eiji Uchida', genre: 'Romance', myRating: 0, imdbRating: 6.8 },
  { id: '95', title: 'Skyfall', year: 2012, director: 'Sam Mendes', genre: 'Action', myRating: 0, imdbRating: 7.8 },
  { id: '96', title: 'Sniper : Legacy', year: 2014, director: 'Don Michael Paul', genre: 'Action', myRating: 0, imdbRating: 5.3 },
  { id: '97', title: 'Sniper White Raven', year: 2022, director: 'Marian Bushan', genre: 'War', myRating: 0, imdbRating: 6.4 },
  { id: '98', title: 'Snowden', year: 2016, director: 'Oliver Stone', genre: 'Thriller', myRating: 0, imdbRating: 7.3 },
  { id: '99', title: 'Spiderman NWH', year: 2021, director: 'Jon Watts', genre: 'Action', myRating: 0, imdbRating: 8.2 },
  { id: '100', title: 'Stalingrad', year: 2013, director: 'Fedor Bondarchuk', genre: 'War', myRating: 0, imdbRating: 5.5 },
  { id: '101', title: 'Suicide Squad', year: 2016, director: 'David Ayer', genre: 'Action', myRating: 0, imdbRating: 5.9 },
  { id: '102', title: 'Sunrise In Heaven', year: 2019, director: 'Waymon Boone', genre: 'Romance', myRating: 0, imdbRating: 6.2 },
  { id: '103', title: 'Takluk Lahad Datu', year: 2024, director: 'Syamsul Yusof', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '104', title: 'Terminator', year: 1984, director: 'James Cameron', genre: 'Sci-Fi', myRating: 10, imdbRating: 8.1 },
  { id: '105', title: 'Terrifier', year: 2016, director: 'Damien Leone', genre: 'Horror', myRating: 0, imdbRating: 5.6 },
  { id: '106', title: 'The Contractor', year: 2022, director: 'Tarik Saleh', genre: 'Action', myRating: 0, imdbRating: 5.8 },
  { id: '107', title: 'The Dark Knight', year: 2008, director: 'Christopher Nolan', genre: 'Action', myRating: 0, imdbRating: 9.0 },
  { id: '108', title: 'The Darkest Hour', year: 2017, director: 'Joe Wright', genre: 'History', myRating: 0, imdbRating: 7.4 },
  { id: '109', title: 'The Day Earth Stood Still', year: 2008, director: 'Scott Derrickson', genre: 'Sci-Fi', myRating: 0, imdbRating: 5.5 },
  { id: '110', title: 'The Devil Wears Prada', year: 2006, director: 'David Frankel', genre: 'Drama', myRating: 0, imdbRating: 7.0 },
  { id: '111', title: 'The Fault In Our Stars', year: 2014, director: 'Josh Boone', genre: 'Romance', myRating: 0, imdbRating: 7.7 },
  { id: '112', title: 'The Imitation Game', year: 2014, director: 'Morten Tyldum', genre: 'History', myRating: 0, imdbRating: 8.0 },
  { id: '113', title: 'The Italian Job', year: 2003, director: 'F. Gary Gray', genre: 'Action', myRating: 0, imdbRating: 7.0 },
  { id: '114', title: 'The Last Of Us', year: 2023, director: 'Craig Mazin', genre: 'Drama', myRating: 0, imdbRating: 8.8 },
  { id: '115', title: 'The Last Summer', year: 2019, director: 'William Bindley', genre: 'Romance', myRating: 0, imdbRating: 5.4 },
  { id: '116', title: 'The Long Walk', year: 2024, director: 'Francis Lawrence', genre: 'Sci-Fi', myRating: 0, imdbRating: 0 },
  { id: '117', title: 'The Matrix', year: 1999, director: 'Wachowskis', genre: 'Sci-Fi', myRating: 0, imdbRating: 8.7 },
  { id: '118', title: 'The Outpost', year: 2020, director: 'Rod Lurie', genre: 'War', myRating: 0, imdbRating: 6.8 },
  { id: '119', title: 'The Pianist', year: 2002, director: 'Roman Polanski', genre: 'History', myRating: 0, imdbRating: 8.5 },
  { id: '120', title: 'The Platform', year: 2019, director: 'Galder Gaztelu-Urrutia', genre: 'Sci-Fi', myRating: 0, imdbRating: 7.0 },
  { id: '121', title: 'The Prosecutor', year: 2014, director: 'N/A', genre: 'Crime', myRating: 0, imdbRating: 0 },
  { id: '122', title: 'The Raid', year: 2011, director: 'Gareth Evans', genre: 'Action', myRating: 0, imdbRating: 7.6 },
  { id: '123', title: 'The Revenger', year: 2018, director: 'Lee Seung-won', genre: 'Action', myRating: 0, imdbRating: 5.7 },
  { id: '124', title: 'The Sadness', year: 2021, director: 'Rob Jabbaz', genre: 'Horror', myRating: 0, imdbRating: 6.5 },
  { id: '125', title: 'The Shadow\'s Edge', year: 2023, director: 'N/A', genre: 'Thriller', myRating: 0, imdbRating: 0 },
  { id: '126', title: 'The Summer I Turned Pretty', year: 2022, director: 'Jenny Han', genre: 'Romance', myRating: 0, imdbRating: 7.3 },
  { id: '127', title: 'Thor Ragnarok', year: 2017, director: 'Taika Waititi', genre: 'Action', myRating: 0, imdbRating: 7.9 },
  { id: '128', title: 'Threads', year: 1984, director: 'Mick Jackson', genre: 'Drama', myRating: 0, imdbRating: 8.0 },
  { id: '129', title: 'Titanic', year: 1997, director: 'James Cameron', genre: 'Romance', myRating: 0, imdbRating: 7.9 },
  { id: '130', title: 'Tom Yum Goong', year: 2005, director: 'Prachya Pinkaew', genre: 'Action', myRating: 0, imdbRating: 7.1 },
  { id: '131', title: 'Top Gun', year: 1986, director: 'Tony Scott', genre: 'Action', myRating: 0, imdbRating: 6.9 },
  { id: '132', title: 'Train To Busan', year: 2016, director: 'Yeon Sang-ho', genre: 'Horror', myRating: 0, imdbRating: 7.6 },
  { id: '133', title: 'Transformers', year: 2007, director: 'Michael Bay', genre: 'Sci-Fi', myRating: 10.0, imdbRating: 7.0 },
  { id: '134', title: 'Trap', year: 2024, director: 'M. Night Shyamalan', genre: 'Thriller', myRating: 0, imdbRating: 5.9 },
  { id: '135', title: 'Tron Ares', year: 2025, director: 'Joachim Rønning', genre: 'Sci-Fi', myRating: 0, imdbRating: 0 },
  { id: '136', title: 'Tron Legacy', year: 2010, director: 'Joseph Kosinski', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.8 },
  { id: '137', title: 'Unfriended', year: 2014, director: 'Levan Gabriadze', genre: 'Horror', myRating: 0, imdbRating: 5.6 },
  { id: '138', title: 'Valkyrie', year: 2008, director: 'Bryan Singer', genre: 'War', myRating: 0, imdbRating: 7.1 },
  { id: '139', title: 'Wall-E', year: 2008, director: 'Andrew Stanton', genre: 'Animation', myRating: 0, imdbRating: 8.4 },
  { id: '140', title: 'Who Am I', year: 2014, director: 'Baran bo Odar', genre: 'Thriller', myRating: 0, imdbRating: 7.5 },
  { id: '141', title: 'Wira', year: 2019, director: 'Adrian Teh', genre: 'Action', myRating: 0, imdbRating: 6.8 },
  { id: '142', title: 'Wolf of Wall Street', year: 2013, director: 'Martin Scorsese', genre: 'Crime', myRating: 0, imdbRating: 8.2 },
  { id: '143', title: 'Wolfenstein', year: 2009, director: 'N/A', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '144', title: 'World War Z', year: 2013, director: 'Marc Forster', genre: 'Horror', myRating: 0, imdbRating: 7.0 },
  { id: '145', title: 'Zero Dark Thirty', year: 2012, director: 'Kathryn Bigelow', genre: 'War', myRating: 0, imdbRating: 7.4 },
  { id: '146', title: 'ZS Justice League', year: 2021, director: 'Zack Snyder', genre: 'Action', myRating: 0, imdbRating: 7.9 },
  { id: '147', title: '2012', year: 2009, director: 'Roland Emmerich', genre: 'Action', myRating: 0, imdbRating: 5.8 },
  { id: '148', title: '50 Shades', year: 2015, director: 'Sam Taylor-Johnson', genre: 'Romance', myRating: 0, imdbRating: 4.1 },
];