// lib/data.ts
export interface Movie {
  id: string;
  title: string;
  year: number;
  director: string;
  genre: string;
  myRating: number;
  imdbRating: number;
  poster?: string;
}

export const GENRES = ['All', 'Sci-Fi', 'Crime', 'Thriller', 'Action', 'Drama', 'War', 'Romance', 'Horror', 'Animation', 'Comedy', 'History'];

export const mockMovies: Movie[] = [
  { id: '1', title: '13 Hours: The Secret Soldiers of Benghazi', year: 2016, director: 'Michael Bay', genre: 'War', myRating: 8.2, imdbRating: 7.3 },
  { id: '2', title: '1917', year: 2019, director: 'Sam Mendes', genre: 'War', myRating: 7.5, imdbRating: 8.2 },
  { id: '3', title: 'A Hidden Life', year: 2019, director: 'Terrence Malick', genre: 'Drama', myRating: 0, imdbRating: 7.4 },
  { id: '4', title: 'Anyone But You', year: 2023, director: 'Will Gluck', genre: 'Romance', myRating: 0, imdbRating: 6.2 },
  { id: '5', title: 'All Quiet On The Western Front', year: 2022, director: 'Edward Berger', genre: 'War', myRating: 0, imdbRating: 7.8 },
  { id: '6', title: 'Allied', year: 2016, director: 'Robert Zemeckis', genre: 'War', myRating: 0, imdbRating: 7.1 },
  { id: '7', title: 'American Made', year: 2017, director: 'Doug Liman', genre: 'Crime', myRating: 0, imdbRating: 7.1 },
  { id: '8', title: 'Culpa Nuestra', year: 2024, director: 'Domingo González', genre: 'Romance', myRating: 0, imdbRating: 5.5},
  { id: '9', title: 'Ballerina', year: 2023, director: 'Lee Chung-hyun', genre: 'Action', myRating: 0, imdbRating: 6.3 },
  { id: '10', title: 'Batman Vs Superman', year: 2016, director: 'Zack Snyder', genre: 'Action', myRating: 0, imdbRating: 6.5 },
  { id: '11', title: 'Battleship', year: 2012, director: 'Peter Berg', genre: 'Sci-Fi', myRating: 0, imdbRating: 5.8 },
  { id: '12', title: 'Baywatch', year: 2017, director: 'Seth Gordon', genre: 'Action', myRating: 0, imdbRating: 5.5 },
  { id: '13', title: 'The Curious Case of Benjamin Button', year: 2008, director: 'David Fincher', genre: 'Drama', myRating: 0, imdbRating: 7.8 },
  { id: '14', title: 'Berlin', year: 2023, director: 'Álex Pina', genre: 'Crime', myRating: 0, imdbRating: 7.0 },
  { id: '15', title: 'Black Adam', year: 2022, director: 'Jaume Collet-Serra', genre: 'Action', myRating: 0, imdbRating: 6.2 },
  { id: '16', title: 'Blood Brothers', year: 2025, director: 'Syafiq Yusof', genre: 'Action', myRating: 0, imdbRating: 7.0 },
  { id: '17', title: 'Call Of Duty: Makarov', year: 2023, director: 'N/A', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '18', title: 'Captain Phillips', year: 2013, director: 'Paul Greengrass', genre: 'Drama', myRating: 0, imdbRating: 7.8 },
  { id: '19', title: 'Chappie', year: 2015, director: 'Neill Blomkamp', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.8, poster: 'https://image.tmdb.org/t/p/w1280/6zmKkfSvo4tBtvGSjn5PofWIvP9.jpg' },
  { id: '20', title: 'Chernobyl', year: 2019, director: 'Johan Renck', genre: 'Drama', myRating: 0, imdbRating: 9.3, poster:'https://image.tmdb.org/t/p/w1280/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg' },
  { id: '21', title: 'Clean House', year: 2019, director: 'Jack O\'Hara', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '22', title: 'Culpa Mia', year: 2023, director: 'Domingo González', genre: 'Romance', myRating: 0, imdbRating: 6.2 },
  { id: '23', title: 'Culpa Tuya', year: 2024, director: 'Domingo González', genre: 'Romance', myRating: 0, imdbRating: 6.0 },
  { id: '24', title: 'Deadpool', year: 2016, director: 'Tim Miller', genre: 'Action', myRating: 0, imdbRating: 8.0 },
  { id: '25', title: 'Deep Impact', year: 1998, director: 'Mimi Leder', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.2 },
  { id: '26', title: 'Devil May Cry', year: 2019, director: 'Hideaki Itsuno', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '27', title: 'Downfall', year: 2004, director: 'Oliver Hirschbiegel', genre: 'History', myRating: 0, imdbRating: 8.2 },
  { id: '28', title: 'Dunkirk', year: 2017, director: 'Christopher Nolan', genre: 'War', myRating: 0, imdbRating: 7.8 },
  { id: '29', title: 'Elemental', year: 2023, director: 'Peter Sohn', genre: 'Animation', myRating: 0, imdbRating: 7.0 },
  { id: '30', title: 'Elysium', year: 2013, director: 'Neill Blomkamp', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.6 },
  { id: '31', title: 'Avengers: Endgame', year: 2019, director: 'Russo Brothers', genre: 'Action', myRating: 0, imdbRating: 8.4, poster: 'https://image.tmdb.org/t/p/w1280/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg' },
  { id: '32', title: 'Escape Plan', year: 2013, director: 'Mikael Håfström', genre: 'Action', myRating: 0, imdbRating: 6.7 },
  { id: '33', title: 'Everest', year: 2015, director: 'Baltasar Kormákur', genre: 'Drama', myRating: 0, imdbRating: 7.1 },
  { id: '34', title: 'Everything Everywhere All At Once', year: 2022, director: 'Daniels', genre: 'Sci-Fi', myRating: 0, imdbRating: 7.8 },
  { id: '35', title: 'Evil Dead Rise', year: 2023, director: 'Lee Cronin', genre: 'Horror', myRating: 0, imdbRating: 6.5 },
  { id: '36', title: 'Extraction', year: 2020, director: 'Sam Hargrave', genre: 'Action', myRating: 0, imdbRating: 6.8 },
  { id: '37', title: 'F1 The Movie', year: 2025, director: 'Joseph Kosinski', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '38', title: 'Fall', year: 2022, director: 'Scott Mann', genre: 'Thriller', myRating: 0, imdbRating: 6.4 },
  { id: '39', title: 'Fast & Furious', year: 2001, director: 'Rob Cohen', genre: 'Action', myRating: 0, imdbRating: 6.8 },
  { id: '40', title: 'Fight Club', year: 1999, director: 'David Fincher', genre: 'Drama', myRating: 0, imdbRating: 8.8 },
  { id: '41', title: 'Five Feet Apart', year: 2019, director: 'Justin Baldoni', genre: 'Romance', myRating: 0, imdbRating: 7.1 },
  { id: '42', title: 'Fury', year: 2014, director: 'David Ayer', genre: 'War', myRating: 0, imdbRating: 7.5 },
  { id: '43', title: 'G.I.Jane', year: 1997, director: 'Ridley Scott', genre: 'Action', myRating: 0, imdbRating: 6.0 },
  { id: '44', title: 'Ghost Of Tsushima', year: 2020, director: 'Nate Fox', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '45', title: 'Greenland', year: 2020, director: 'Ric Roman Waugh', genre: 'Thriller', myRating: 0, imdbRating: 6.4 },
  { id: '46', title: 'Hacker', year: 2016, director: 'Akan Satayev', genre: 'Crime', myRating: 0, imdbRating: 6.1 },
  { id: '47', title: 'Harley Quinn', year: 2019, director: 'Justin Halpern', genre: 'Action', myRating: 0, imdbRating: 8.4 },
  { id: '48', title: 'Havoc', year: 2025, director: 'Gareth Evans', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '49', title: 'High Council', year: 2023, director: 'N/A', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '50', title: 'In Youth We Trust', year: 2018, director: 'N/A', genre: 'Drama', myRating: 0, imdbRating: 0 },
  { id: '51', title: 'Inception', year: 2010, director: 'Christopher Nolan', genre: 'Sci-Fi', myRating: 10.0, imdbRating: 8.8, poster: 'https://image.tmdb.org/t/p/w1280/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg' },
  { id: '52', title: 'Avengers: Infinity War', year: 2018, director: 'Russo Brothers', genre: 'Action', myRating: 0, imdbRating: 8.4 },
  { id: '53', title: 'Interstellar', year: 2014, director: 'Christopher Nolan', genre: 'Sci-Fi', myRating: 9.0, imdbRating: 8.7 },
  { id: '54', title: 'Iron Man', year: 2008, director: 'Jon Favreau', genre: 'Action', myRating: 0, imdbRating: 7.9 },
  { id: '55', title: 'John Wick', year: 2014, director: 'Chad Stahelski', genre: 'Action', myRating: 0, imdbRating: 7.4 },
  { id: '56', title: 'Joker', year: 2019, director: 'Todd Phillips', genre: 'Crime', myRating: 0, imdbRating: 8.4 },
  { id: '57', title: 'Jurassic World', year: 2015, director: 'Colin Trevorrow', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.9 },
  { id: '58', title: 'Kahar', year: 2024, director: 'Razaisyam Rashid', genre: 'Action', myRating: 0, imdbRating: 7.2 },
  { id: '59', title: 'Kingsman', year: 2014, director: 'Matthew Vaughn', genre: 'Action', myRating: 0, imdbRating: 7.7 },
  { id: '60', title: 'KL Gangster', year: 2011, director: 'Syamsul Yusof', genre: 'Action', myRating: 0, imdbRating: 6.1 },
  { id: '61', title: 'Look Who\'s Back', year: 2015, director: 'David Wnendt', genre: 'Comedy', myRating: 0, imdbRating: 7.0 },
  { id: '62', title: 'Lucifer', year: 2016, director: 'Tom Kapinos', genre: 'Crime', myRating: 0, imdbRating: 8.1 },
  { id: '63', title: 'Mad Max', year: 2015, director: 'George Miller', genre: 'Action', myRating: 0, imdbRating: 8.1 },
  { id: '64', title: 'Malam Terlarang', year: 2025, director: 'N/A', genre: 'Horror', myRating: 0, imdbRating: 0 },
  { id: '65', title: 'Mat Kilau', year: 2022, director: 'Syamsul Yusof', genre: 'History', myRating: 0, imdbRating: 5.4 },
  { id: '66', title: 'Meet Joe Black', year: 1998, director: 'Martin Brest', genre: 'Drama', myRating: 0, imdbRating: 7.2 },
  { id: '67', title: 'Mission Impossible', year: 1996, director: 'Brian De Palma', genre: 'Action', myRating: 0, imdbRating: 7.1 },
  { id: '68', title: 'MK11', year: 2019, director: 'N/A', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '69', title: 'Money Heist', year: 2017, director: 'Álex Pina', genre: 'Crime', myRating: 10.0, imdbRating: 8.2, poster: 'https://image.tmdb.org/t/p/w1280/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg' },
  { id: '70', title: 'Mr & Mrs Smith', year: 2005, director: 'Doug Liman', genre: 'Action', myRating: 0, imdbRating: 6.5 },
  { id: '71', title: 'Need For Speed', year: 2014, director: 'Scott Waugh', genre: 'Action', myRating: 0, imdbRating: 6.4 },
  { id: '72', title: 'The Night Comes For Us', year: 2018, director: 'Timo Tjahjanto', genre: 'Action', myRating: 0, imdbRating: 6.9, poster: 'https://image.tmdb.org/t/p/w1280/tg51bzNtM1yzwVkXSCPpsgBuGZb.jpg' },
  { id: '73', title: 'Ninja Assassin', year: 2009, director: 'James McTeigue', genre: 'Action', myRating: 0, imdbRating: 6.3, poster: 'https://image.tmdb.org/t/p/w1280/5twFaR5A1Y9C3KAt6uy6iq332m0.jpg' },
  { id: '74', title: 'Now You See Me', year: 2013, director: 'Louis Leterrier', genre: 'Thriller', myRating: 0, imdbRating: 7.2, poster: 'https://image.tmdb.org/t/p/w1280/tWsNYbrqy1p1w6K9zRk0mSchztT.jpg' },
  { id: '75', title: 'Nowhere', year: 2023, director: 'Albert Pintó', genre: 'Thriller', myRating: 0, imdbRating: 6.4 },
  { id: '76', title: 'Olympus Has Fallen', year: 2013, director: 'Antoine Fuqua', genre: 'Action', myRating: 0, imdbRating: 6.5 },
  { id: '77', title: 'Once Upon A Time In Hollywood', year: 2019, director: 'Quentin Tarantino', genre: 'Drama', myRating: 0, imdbRating: 7.6 },
  { id: '78', title: 'Ong Bak', year: 2003, director: 'Prachya Pinkaew', genre: 'Action', myRating: 0, imdbRating: 7.1 },
  { id: '79', title: 'Operation Fortune: Ruse De Guere', year: 2023, director: 'Guy Ritchie', genre: 'Action', myRating: 0, imdbRating: 6.3 },
  { id: '80', title: 'Oppenheimer', year: 2023, director: 'Christopher Nolan', genre: 'History', myRating: 0, imdbRating: 8.3 },
  { id: '81', title: 'Our Beloved Summer', year: 2021, director: 'Kim Yoon-jin', genre: 'Romance', myRating: 0, imdbRating: 8.2 },
  { id: '82', title: 'Pacific Rim', year: 2013, director: 'Guillermo del Toro', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.9 },
  { id: '83', title: 'Parasite', year: 2019, director: 'Bong Joon-ho', genre: 'Thriller', myRating: 0, imdbRating: 8.5 },
  { id: '84', title: 'Paskal', year: 2018, director: 'Adrian Teh', genre: 'Action', myRating: 0, imdbRating: 7.7 },
  { id: '85', title: 'Peaky Blinders', year: 2013, director: 'Steven Knight', genre: 'Crime', myRating: 0, imdbRating: 8.8 },
  { id: '86', title: 'Purple Hearts', year: 2022, director: 'Elizabeth Allen Rosenbaum', genre: 'Romance', myRating: 0, imdbRating: 6.7 },
  { id: '87', title: 'Rambo', year: 1982, director: 'Ted Kotcheff', genre: 'Action', myRating: 0, imdbRating: 7.7 },
  { id: '88', title: 'Robocop', year: 1987, director: 'Paul Verhoeven', genre: 'Sci-Fi', myRating: 0, imdbRating: 7.6 },
  { id: '89', title: 'San Andreas', year: 2015, director: 'Brad Peyton', genre: 'Action', myRating: 0, imdbRating: 6.0 },
  { id: '90', title: 'Saving Private Ryan', year: 1998, director: 'Steven Spielberg', genre: 'War', myRating: 0, imdbRating: 8.6 },
  { id: '91', title: 'Shawshank Redemption', year: 1994, director: 'Frank Darabont', genre: 'Drama', myRating: 0, imdbRating: 9.3 },
  { id: '92', title: 'Sheriff', year: 2024, director: 'Syafiq Yusof', genre: 'Crime', myRating: 0, imdbRating: 7.8 },
  { id: '93', title: 'Sicario', year: 2015, director: 'Denis Villeneuve', genre: 'Action', myRating: 10.0, imdbRating: 7.7, poster: 'https://image.tmdb.org/t/p/w1280/lz8vNyXeidqqOdJW9ZjnDAMb5Vr.jpg' },
  { id: '94', title: 'Silent Love', year: 2024, director: 'Eiji Uchida', genre: 'Romance', myRating: 0, imdbRating: 6.8 },
  { id: '95', title: 'Skyfall', year: 2012, director: 'Sam Mendes', genre: 'Action', myRating: 0, imdbRating: 7.8 },
  { id: '96', title: 'Sniper: Legacy', year: 2014, director: 'Don Michael Paul', genre: 'Action', myRating: 0, imdbRating: 5.3 },
  { id: '97', title: 'Sniper: White Raven', year: 2022, director: 'Marian Bushan', genre: 'War', myRating: 0, imdbRating: 6.4 },
  { id: '98', title: 'Snowden', year: 2016, director: 'Oliver Stone', genre: 'Thriller', myRating: 0, imdbRating: 7.3 },
  { id: '99', title: 'Spiderman: No Way Home', year: 2021, director: 'Jon Watts', genre: 'Action', myRating: 0, imdbRating: 8.2 },
  { id: '100', title: 'Stalingrad', year: 1993, director: 'Joseph Vilsmaier', genre: 'War', myRating: 0, imdbRating: 7.5, poster: 'https://image.tmdb.org/t/p/w1280/hEHmXFMOBJv5c6Gd5m6mDiLAxsy.jpg' },
  { id: '101', title: 'Suicide Squad', year: 2016, director: 'David Ayer', genre: 'Action', myRating: 0, imdbRating: 5.9 },
  { id: '102', title: 'Sunrise In Heaven', year: 2019, director: 'Waymon Boone', genre: 'Romance', myRating: 0, imdbRating: 6.2 },
  { id: '103', title: 'Takluk: Lahad Datu', year: 2024, director: 'Zulkarnain Azhar', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '104', title: 'Terminator', year: 1984, director: 'James Cameron', genre: 'Sci-Fi', myRating: 10, imdbRating: 8.1, poster: 'https://image.tmdb.org/t/p/w1280/qvktm0BHcnmDpul4Hz01GIazWPr.jpg' },
  { id: '105', title: 'Terrifier', year: 2016, director: 'Damien Leone', genre: 'Horror', myRating: 0, imdbRating: 5.6 },
  { id: '106', title: 'The Contractor', year: 2022, director: 'Tarik Saleh', genre: 'Action', myRating: 0, imdbRating: 5.8 },
  { id: '107', title: 'The Dark Knight', year: 2008, director: 'Christopher Nolan', genre: 'Action', myRating: 0, imdbRating: 9.0 },
  { id: '108', title: 'The Darkest Hour', year: 2017, director: 'Joe Wright', genre: 'History', myRating: 0, imdbRating: 7.4 },
  { id: '109', title: 'The Day Earth Stood Still', year: 2008, director: 'Scott Derrickson', genre: 'Sci-Fi', myRating: 0, imdbRating: 5.5 },
  { id: '110', title: 'The Devil Wears Prada', year: 2006, director: 'David Frankel', genre: 'Drama', myRating: 0, imdbRating: 7.0 },
  { id: '111', title: 'The Fault In Our Stars', year: 2014, director: 'Josh Boone', genre: 'Romance', myRating: 0, imdbRating: 7.7 },
  { id: '112', title: 'The Imitation Game', year: 2014, director: 'Morten Tyldum', genre: 'History', myRating: 0, imdbRating: 8.0, poster: 'https://image.tmdb.org/t/p/w1280/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg' },
  { id: '113', title: 'The Italian Job', year: 2003, director: 'F. Gary Gray', genre: 'Action', myRating: 0, imdbRating: 7.0 },
  { id: '114', title: 'The Last Of Us', year: 2023, director: 'Craig Mazin', genre: 'Drama', myRating: 0, imdbRating: 8.8 },
  { id: '115', title: 'The Last Summer', year: 2019, director: 'William Bindley', genre: 'Romance', myRating: 0, imdbRating: 5.4 },
  { id: '116', title: 'The Long Walk', year: 2024, director: 'Francis Lawrence', genre: 'Sci-Fi', myRating: 0, imdbRating: 0 },
  { id: '117', title: 'The Matrix', year: 1999, director: 'Wachowskis', genre: 'Sci-Fi', myRating: 0, imdbRating: 8.7, poster: 'https://image.tmdb.org/t/p/w1280/p96dm7sCMn4VYAStA6siNz30G1r.jpg' },
  { id: '118', title: 'The Outpost', year: 2020, director: 'Rod Lurie', genre: 'War', myRating: 0, imdbRating: 6.8 },
  { id: '119', title: 'The Pianist', year: 2002, director: 'Roman Polanski', genre: 'History', myRating: 0, imdbRating: 8.5 },
  { id: '120', title: 'The Platform', year: 2019, director: 'Galder Gaztelu-Urrutia', genre: 'Sci-Fi', myRating: 0, imdbRating: 7.0, poster: 'https://image.tmdb.org/t/p/w1280/iXvQnzy6JCAx1PiQEKXuTY04ZHl.jpg' },
  { id: '121', title: 'The Prosecutor', year: 2014, director: 'N/A', genre: 'Crime', myRating: 0, imdbRating: 0 },
  { id: '122', title: 'The Raid', year: 2011, director: 'Gareth Evans', genre: 'Action', myRating: 0, imdbRating: 7.6 },
  { id: '123', title: 'The Revenger', year: 2018, director: 'Lee Seung-won', genre: 'Action', myRating: 0, imdbRating: 5.7 },
  { id: '124', title: 'The Sadness', year: 2021, director: 'Rob Jabbaz', genre: 'Horror', myRating: 0, imdbRating: 6.5 },
  { id: '125', title: 'The Shadow\'s Edge', year: 2023, director: 'N/A', genre: 'Thriller', myRating: 0, imdbRating: 0 },
  { id: '126', title: 'The Summer I Turned Pretty', year: 2022, director: 'Jenny Han', genre: 'Romance', myRating: 0, imdbRating: 7.3 },
  { id: '127', title: 'Thor Ragnarok', year: 2017, director: 'Taika Waititi', genre: 'Action', myRating: 0, imdbRating: 7.9 },
  { id: '128', title: 'Threads', year: 1984, director: 'Mick Jackson', genre: 'Drama', myRating: 0, imdbRating: 8.0 },
  { id: '129', title: 'Titanic', year: 1997, director: 'James Cameron', genre: 'Romance', myRating: 0, imdbRating: 7.9 },
  { id: '130', title: 'Tom Yum Goong', year: 2005, director: 'Prachya Pinkaew', genre: 'Action', myRating: 0, imdbRating: 7.1 },
  { id: '131', title: 'Top Gun', year: 1986, director: 'Tony Scott', genre: 'Action', myRating: 0, imdbRating: 6.9 },
  { id: '132', title: 'Train To Busan', year: 2016, director: 'Yeon Sang-ho', genre: 'Horror', myRating: 0, imdbRating: 7.6 },
  { id: '133', title: 'Transformers', year: 2007, director: 'Michael Bay', genre: 'Sci-Fi', myRating: 10.0, imdbRating: 7.0 },
  { id: '134', title: 'Trap', year: 2024, director: 'M. Night Shyamalan', genre: 'Thriller', myRating: 0, imdbRating: 5.9 },
  { id: '135', title: 'Tron: Ares', year: 2025, director: 'Joachim Rønning', genre: 'Sci-Fi', myRating: 0, imdbRating: 0, poster: 'https://image.tmdb.org/t/p/w1280/chpWmskl3aKm1aTZqUHRCtviwPy.jpg' },
  { id: '136', title: 'Tron: Legacy', year: 2010, director: 'Joseph Kosinski', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.8, poster: 'https://image.tmdb.org/t/p/w1280/vuifSABRpSnxCAOxEnWpNbZSXpp.jpg' },
  { id: '137', title: 'Unfriended', year: 2014, director: 'Levan Gabriadze', genre: 'Horror', myRating: 0, imdbRating: 5.6 },
  { id: '138', title: 'Valkyrie', year: 2008, director: 'Bryan Singer', genre: 'War', myRating: 0, imdbRating: 7.1 },
  { id: '139', title: 'Wall-E', year: 2008, director: 'Andrew Stanton', genre: 'Animation', myRating: 0, imdbRating: 8.4 },
  { id: '140', title: 'Who Am I: No System Is Safe', year: 2014, director: 'Baran bo Odar', genre: 'Thriller', myRating: 0, imdbRating: 7.5, poster: 'https://image.tmdb.org/t/p/w1280/oR3tbNzJMJmCKS5O5fanU9yxIOk.jpg' },
  { id: '141', title: 'Wira', year: 2019, director: 'Adrian Teh', genre: 'Action', myRating: 0, imdbRating: 6.8 },
  { id: '142', title: 'Wolf of Wall Street', year: 2013, director: 'Martin Scorsese', genre: 'Crime', myRating: 0, imdbRating: 8.2 },
  { id: '143', title: 'Wolfenstein', year: 2009, director: 'N/A', genre: 'Action', myRating: 0, imdbRating: 0 },
  { id: '144', title: 'World War Z', year: 2013, director: 'Marc Forster', genre: 'Horror', myRating: 0, imdbRating: 7.0 },
  { id: '145', title: 'Zero Dark Thirty', year: 2012, director: 'Kathryn Bigelow', genre: 'War', myRating: 0, imdbRating: 7.4, poster: 'https://image.tmdb.org/t/p/w1280/wNSdSSxowM3WIqmPJNg3RagYbwP.jpg' },
  { id: '146', title: 'Zack Snyder Justice League', year: 2021, director: 'Zack Snyder', genre: 'Action', myRating: 0, imdbRating: 7.9 },
  { id: '147', title: '2012', year: 2009, director: 'Roland Emmerich', genre: 'Action', myRating: 0, imdbRating: 5.8 },
  { id: '148', title: 'The Map That Leads to You', year: 2025, director: 'Lasse Hallström', genre: 'Romance', myRating: 0, imdbRating: 6.2 },
  { id: '149', title: 'Sicario: Day of the Soldado', year: 2018, director: 'Stefano Sollima', genre: 'Action', myRating: 0, imdbRating: 7.1 },
  { id: '150', title: 'Terminator 2: Judgment Day', year: 1991, director: 'James Cameron', genre: 'Sci-Fi', myRating: 0, imdbRating: 8.6, poster:'https://image.tmdb.org/t/p/w1280/jFTVD4XoWQTcg7wdyJKa8PEds5q.jpg' },
  { id: '151', title: 'Transformers: Revenge of the Fallen', year: 2009, director: 'Michael Bay', genre: 'Sci-Fi', myRating: 0, imdbRating: 5.9 },
  { id: '152', title: 'Transformers: Dark of the Moon', year: 2011, director: 'Michael Bay', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.2, poster:'https://media.themoviedb.org/t/p/w188_and_h282_face/28YlCLrFhONteYSs9hKjD1Km0Cj.jphttps://media.themoviedb.org/t/p/w600_and_h900_face/28YlCLrFhONteYSs9hKjD1Km0Cj.jpg' },
  { id: '153', title: 'Transformers: Age of Extinction', year: 2014, director: 'Michael Bay', genre: 'Sci-Fi', myRating: 0, imdbRating: 5.6 },
  { id: '154', title: 'Transformers: The Last Knight', year: 2017, director: 'Michael Bay', genre: 'Sci-Fi', myRating: 0, imdbRating: 5.2 },
  { id: '155', title: 'The Dark Knight Rises', year: 2012, director: 'Christopher Nolan', genre: 'Action', myRating: 0, imdbRating: 8.4 },
  { id: '156', title: 'Extraction 2', year: 2023, director: 'Sam Hargrave', genre: 'Action', myRating: 0, imdbRating: 7.0, poster:'https://image.tmdb.org/t/p/w1280/d1qDrtlRP3adVFhGlGiLLMutmRd.jpg' },
  { id: '157', title: '2 Fast 2 Furious', year: 2003, director: 'John Singleton', genre: 'Action', myRating: 0, imdbRating: 5.9 },
  { id: '158', title: 'The Fast and the Furious: Tokyo Drift', year: 2006, director: 'Justin Lin', genre: 'Action', myRating: 0, imdbRating: 6.0 },
  { id: '159', title: 'Fast & Furious', year: 2009, director: 'Justin Lin', genre: 'Action', myRating: 0, imdbRating: 6.5 },
  { id: '160', title: 'Fast Five', year: 2011, director: 'Justin Lin', genre: 'Action', myRating: 0, imdbRating: 7.3 },
  { id: '161', title: 'Fast & Furious 6', year: 2013, director: 'Justin Lin', genre: 'Action', myRating: 0, imdbRating: 7.0 },
  { id: '162', title: 'Furious 7', year: 2015, director: 'James Wan', genre: 'Action', myRating: 0, imdbRating: 7.1 },
  { id: '163', title: 'The Fate of the Furious', year: 2017, director: 'F. Gary Gray', genre: 'Action', myRating: 0, imdbRating: 6.6 },
  { id: '164', title: 'F9: The Fast Saga', year: 2021, director: 'Justin Lin', genre: 'Action', myRating: 0, imdbRating: 5.2 },
  { id: '165', title: 'Fast X', year: 2023, director: 'Louis Leterrier', genre: 'Action', myRating: 0, imdbRating: 5.8 },
  { id: '166', title: 'Iron Man 2', year: 2010, director: 'Jon Favreau', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.9 },
  { id: '167', title: 'Iron Man 3', year: 2013, director: 'Shane Black', genre: 'Sci-Fi', myRating: 0, imdbRating: 7.1 },
  { id: '168', title: 'John Wick: Chapter 2', year: 2017, director: 'Chad Stahelski', genre: 'Action', myRating: 0, imdbRating: 7.4 },
  { id: '169', title: 'John Wick: Chapter 3 - Parabellum', year: 2019, director: 'Chad Stahelski', genre: 'Action', myRating: 0, imdbRating: 7.4 },
  { id: '170', title: 'John Wick: Chapter 4', year: 2023, director: 'Chad Stahelski', genre: 'Action', myRating: 0, imdbRating: 7.7, poster:'https://image.tmdb.org/t/p/w1280/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg' },
  { id: '171', title: 'Jurassic World Dominion', year: 2022, director: 'Colin Trevorrow', genre: 'Sci-Fi', myRating: 0, imdbRating: 5.6 },
  { id: '172', title: 'Jurassic World Rebirth', year: 2025, director: 'Gareth Edwards', genre: 'Sci-Fi', myRating: 0, imdbRating: 5.8 },
  { id: '173', title: 'Mission: Impossible II', year: 2000, director: 'John Woo', genre: 'Action', myRating: 0, imdbRating: 6.1 },
  { id: '174', title: 'Mission: Impossible III', year: 2006, director: 'J.J. Abrams', genre: 'Action', myRating: 0, imdbRating: 6.9 },
  { id: '175', title: 'Mission: Impossible: Ghost Protocol', year: 2011, director: 'Brad Bird', genre: 'Action', myRating: 0, imdbRating: 7.4 },
  { id: '176', title: 'Mission: Impossible: Rogue Nation', year: 2015, director: 'Christopher McQuarrie', genre: 'Action', myRating: 0, imdbRating: 7.4 },
  { id: '177', title: 'Mission: Impossible: Fallout', year: 2018, director: 'Christopher McQuarrie', genre: 'Action', myRating: 0, imdbRating: 7.7, poster:'https://image.tmdb.org/t/p/w1280/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg' },
  { id: '178', title: 'Mission: Impossible: Dead Reckoning Part One', year: 2023, director: 'Christopher McQuarrie', genre: 'Action', myRating: 0, imdbRating: 7.7 },
  { id: '179', title: 'Mission: Impossible: Dead Reckoning Part Two', year: 2025, director: 'Christopher McQuarrie', genre: 'Action', myRating: 0, imdbRating: 7.9 },
  { id: '180', title: 'Now You See Me 2', year: 2016, director: 'Jon M. Chu', genre: 'Crime', myRating: 0, imdbRating: 6.4 },
  { id: '181', title: 'Now You See Me: Now You Don\'t', year: 2025, director: 'Ruben Fleischer', genre: 'Crime', myRating: 0, imdbRating: 6.2 },
  { id: '182', title: 'American Sniper', year: 2014, director: 'Clint Eastwood', genre: 'War', myRating: 0, imdbRating: 7.3 },
  { id: '183', title: 'The Godfather', year: 1972, director: 'Francis Ford Coppola', genre: 'Crime', myRating: 0, imdbRating: 9.2 },
  { id: '184', title: 'The Godfather Part II', year: 1974, director: 'Francis Ford Coppola', genre: 'Crime', myRating: 0, imdbRating: 9.0 },
  { id: '185', title: 'Terrifier 3', year: 2024, director: 'Damien Leone', genre: 'Horror', myRating: 0, imdbRating: 6.8 },
  { id: '186', title: 'Incantation', year: 2022, director: 'Kevin Ko', genre: 'Horror', myRating: 0, imdbRating: 6.2 },
  { id: '187', title: 'The Matrix Reloaded', year: 2003, director: 'The Wachowskis', genre: 'Sci-Fi', myRating: 0, imdbRating: 7.2 },
  { id: '188', title: 'Inglourious Basterds', year: 2009, director: 'Quentin Tarantino', genre: 'War', myRating: 0, imdbRating: 8.4 },
  { id: '189', title: 'My Oxford Year', year: 2025, director: 'Iain Morris', genre: 'Romance', myRating: 0, imdbRating: 5.7 },
  { id: '190', title: 'Kingsman: The Golden Circle', year: 2017, director: 'Matthew Vaughn', genre: 'Action', myRating: 0, imdbRating: 6.7 },
  { id: '191', title: 'Blade Runner 2049', year: 2017, director: 'Denis Villeneuve', genre: 'Sci-Fi', myRating: 0, imdbRating: 8.0, poster:'https://image.tmdb.org/t/p/w1280/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg' },
  { id: '192', title: 'Seobok', year: 2021, director: 'Lee Yong-ju', genre: 'Sci-Fi', myRating: 0, imdbRating: 6.1 },
  { id: '193', title: 'The Savant', year: 2026, director: 'Matthew Heineman', genre: 'Crime', myRating: 0, imdbRating: 7.2 },
  { id: '194', title: 'Upgrade', year: 2018, director: 'Leigh Whannell', genre: 'Sci-Fi', myRating: 0, imdbRating: 7.5 },
  { id: '195', title: 'Taken', year: 2008, director: 'Pierre Morel', genre: 'Action', myRating: 0, imdbRating: 7.7 },
  { id: '196', title: 'The Revenant', year: 2015, director: 'Alejandro González Iñárritu', genre: 'Action', myRating: 0, imdbRating: 8.0 },
  { id: '197', title: 'Tinker Tailor Soldier Spy', year: 2011, director: 'Tomas Alfredson', genre: 'Thriller', myRating: 0, imdbRating: 7.0, poster: 'https://image.tmdb.org/t/p/w1280/e0dZ7TapGY9HtJ9xk1TUHPEOccl.jpg' },
  { id: '198', title: 'Riverdale', year: 2017, director: 'Roberto Aguirre-Sacasa', genre: 'Crime', myRating: 0, imdbRating: 6.5 },
  { id: '199', title: 'The Martian', year: 2015, director: 'Ridley Scott', genre: 'Sci-Fi', myRating: 0, imdbRating: 8.0 },
  { id: '200', title: 'The Last of Us Part II', year: 2025, director: 'Craig Mazin', genre: 'Horror', myRating: 0, imdbRating: 8.9 },
  { id: '201', title: 'My Life with the Walter Boys', year: 2023, director: 'Melanie Halsall', genre: 'Romance', myRating: 0, imdbRating: 6.8 },
  { id: '202', title: 'The Day of the Jackal', year: 2024, director: 'Brian Kirk', genre: 'Crime', myRating: 0, imdbRating: 7.9 },
  { id: '203', title: 'Se7en', year: 1995, director: 'David Fincher', genre: 'Crime', myRating: 0, imdbRating: 8.6, poster:'https://image.tmdb.org/t/p/w1280/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg' },
  { id: '204', title: 'Grave of the Fireflies', year: 1988, director: 'Isao Takahata', genre: 'War', myRating: 0, imdbRating: 8.5, poster: 'https://image.tmdb.org/t/p/w1280/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg' },
  { id: '205', title: 'Requiem for a Dream', year: 2000, director: 'Darren Aronofsky', genre: 'Crime', myRating: 0, imdbRating: 8.3 },
  { id: '206', title: 'Baby Driver', year: 2017, director: 'Edgar Wright', genre: 'Action', myRating: 0, imdbRating: 7.5 },
  { id: '207', title: 'One Battle After Another', year: 2025, director: 'Zhang Yimou', genre: 'Thriller', myRating: 0, imdbRating: 7.1 },
  { id: '208', title: 'Unfriended: Dark Web', year: 2018, director: 'Stephen Susco', genre: 'Horror', myRating: 0, imdbRating: 6.0 }
];